- .gitignore
- tools/deploy.py
- tools/export_classnames.py
- Add Python script for exporting classnames
- Add preparations for automated wiki page updating through Travis (requires https://github.com/PyGithub/PyGithub/pull/379)
> Add export classnames tool

- meta.cpp
- tools/make.py
- Add support for Steam Workshop item for server browser
- Close #33 
- Add new `meta.cpp` file to `importantFiles` list in `make.py`
> Add Steam Workshop server browser support

- addons/units/CfgVehicles_HelperUnits.hpp
> Fix underwear not available to all sides

- addons/main/CfgMods.hpp
- Close #47 
- Use `Q` macros in `CfgMods` (wasn't used for whatever reason)
> Use Q macros in CfgMods

- addons/glasses/data/glass_pass2.rvmat
- addons/glasses/data/reflective_glass.rvmat
- addons/headgear/data/earpiece_cord.rvmat
- addons/units/data/uniform_combat.rvmat
- addons/units/data/uniform_combat_checked.rvmat
- addons/units/data/uniform_polo.rvmat
- addons/units/data/vip.rvmat
- Close #48 
- Braces on same line as class/property
- Spaces instead of tabs
- Spaces in arrays and around `=`
> Prettify material files

- addons/main/script_mod.hpp
- addons/main/script_version.hpp
- tools/make.py
> Update make.py to 0.8, Split version to separate file

- optionals/variants_melb/config.cpp
> Fix BLUFOR MELBs not showing in Zeus

- addons/backpacks/stringtable.xml
- addons/glasses/stringtable.xml
- addons/headgear/stringtable.xml
- addons/main/stringtable.xml
- addons/units/stringtable.xml
- addons/vehicles/stringtable.xml
- addons/vests/stringtable.xml
- addons/weapons/stringtable.xml
- optionals/variants_melb/stringtable.xml
Japanese translation for mods.
> Jpn translation

- optionals/variants_melb/$PBOPREFIX$
- Fixes not-working MELB Variants textures
> Fix MELB Variants PBOPREFIX

- .travis.yml
- tools/deploy.py
- tools/export_classnames.py
- Title
- Close #26 #56 
Todo:
> Add automatic Class Names page updating to Travis deploy script

- addons/weapons/CfgWeapons.hpp
> Add baseWeapon config entry (required for Virtual Arsenal)

- addons/units/stringtable.xml
> Rework uniform names

- addons/units/CfgVehicles_GroundItems.hpp
- Fix issue introduced in #66 - mistakenly removed uniform item
> Fix mistakenly removed uniform item

- addons/units/stringtable.xml
Rework uniform names as requested in #61.
> Shorter german uniform names

- tools/make.py
> Update make.py to 0.9, Build optionals as launchable mod folders

- AUTHORS.txt
> Added new authors

- tools/make.py
- Title
_Kresky made me be annoyed by it not being the same as main mod folder._
> Use proper prefix name for optionals

- AUTHORS.txt
- addons/insignias/CfgUnitInsignia.hpp
- addons/insignias/config.cpp
- optionals/variants_bwa3/CfgVehicles.hpp
- optionals/variants_bwa3/README.md
- optionals/variants_bwa3/config.cpp
- Put Theseus members as Core Team
- Add missing Contributors
- Rename Old Man to GilleeDoo
> Rework Authors

- addons/backpacks/stringtable.xml
- addons/glasses/stringtable.xml
- addons/headgear/stringtable.xml
- addons/main/stringtable.xml
- addons/units/stringtable.xml
- addons/vehicles/stringtable.xml
- addons/vests/stringtable.xml
- addons/weapons/stringtable.xml
- optionals/variants_bwa3/stringtable.xml
- optionals/variants_melb/stringtable.xml
- Add french translations for all modules
- Fix a typo in the `STR_TACS_Units_Uniform_TShirt_JP_GS_LP_BB` string, the middle color is blue, not white.
> Add french translations for all modules

- optionals/variants_bwa3/CfgVehicles.hpp
- optionals/variants_bwa3/stringtable.xml
- Use VhC texture handling
- Introduce a bunch of new strings for textures
> Update/Fix BWA3 Eagle IV variants for BWA3 v2.0

- addons/backpacks/stringtable.xml
- addons/glasses/stringtable.xml
- addons/headgear/stringtable.xml
- addons/vehicles/stringtable.xml
- addons/vests/stringtable.xml
- addons/weapons/stringtable.xml
- optionals/variants_bwa3/stringtable.xml
- optionals/variants_melb/stringtable.xml
- Add all german translations
-Unify spelling of colors
> Finished the German translation, spellcheck

- addons/headgear/CfgVehicles.hpp
- addons/headgear/CfgWeapons.hpp
- Fix no name
- Fix no actual wearable in the item
- Fix no wearable in the Wearables box
Follow-up to #93.
> Fix Theseus Beret

- .travis.yml
- addons/insignias/CfgUnitInsignia.hpp
- addons/units/CfgVehicles_PublicUnits.hpp
- tools/config_style_checker.py
- tools/stringtableduplicates.py
- Title
- Run config style checker instead of SQF validator on Travis
> Remove SQF Validator, Add Config style and Stringtable duplicates checkers

- addons/insignias/CfgUnitInsignia.hpp
> Fix insignias config

- addons/units/CfgVehicles_PublicUnits.hpp
- addons/units/script_component.hpp
Adds the following items to units when placing them:
Compass
Map
Watch
> Add Compass, Map and Watch to contractor units

- addons/headgear/CfgVehicles.hpp
- addons/main/CfgMods.hpp
- addons/main/script_macros.hpp
- addons/units/CfgGroups.hpp
- addons/units/CfgVehicles_HelperUnits.hpp
- addons/units/CfgVehicles_PublicUnits.hpp
- addons/vehicles/CfgVehicles.hpp
- build.bat
- optionals/variants_bwa3/CfgVehicles.hpp
- optionals/variants_melb/CfgVehicles.hpp
- optionals/variants_melb/data/melb_clear_ext.rvmat
- Quote all strings properly (HEMTT/armake2 warnings)
- Fix `CfgMods` author string config entry
- Add quick build batch script
> Quote all strings properly (HEMTT/armake2 warnings)

- addons/units/CfgVehicles_HelperUnits.hpp
Plaid should now show correctly.
- Tested and is working.
> Fixed Rolled Plaid uniform base models

- addons/units/config.cpp
- Added Marksman unit to config.cpp
> Fixed Zeus groups not showing

- addons/vests/CfgVehicles.hpp
- addons/vests/CfgWeapons.hpp
- Fix Plate Carrier retextures (f9da60ac1bdebc049d5ea4148c0aae8688b5b6ce regression)
- Cleanup Tactical Vest config
- Add comments to vests component
> Fix Plate Carrier retextures (regression)

- addons/units/CfgVehicles_PublicUnits.hpp
- Replace #112 when https://github.com/CBATeam/CBA_A3/pull/1201 releases
- Close #24 
- Set default headgear properly - for when randomization is disabled.
**Merge after https://github.com/CBATeam/CBA_A3/pull/1201 is released!**
> Add facewear randomization (CBA)

- addons/main/script_macros.hpp
- Title
**Merge after https://github.com/CBATeam/CBA_A3/pull/1221 is released!**
> Use CBA Versioning System properly

- addons/weapons/CfgWeapons.hpp
- Fixed the Theseus MX camo variant using Sand/Tan mags and now uses black.
> Theseus MX Magazine fix

- optionals/arcadian/CfgVehicles.hpp
- Removes our "Rear Gunner" seat fix, CUP update will fix this.
> Remove Rear Gunner fix

- optionals/arcadian/CfgVehicles.hpp
- Title (regression from #126)
> Arcadian - Fix side mounts removal

- optionals/arcadian/CfgVehicles.hpp
> Arcadian - Fix side mounts removal (proper)

- addons/units/CfgVehicles_HelperUnits.hpp
- Most recently added plaid uniforms had a texture clipping issue with a zipper that shouldn't have been there, updated base class and fixed.
> Fix Plaid uniforms zipper clipping (base class change)

- addons/backpacks/CfgVehicles.hpp
> Fix RGR Assault Pakc texture path

- optionals/arcadian/CfgVehicles.hpp
Improves visibility for the driver with a brighter and further reaching light.
**Before:**
**After**
> Arcadian - Upgrade headlights to LED

- optionals/arcadian/CfgVehicles.hpp
> Arcadian - Increase default cargo space from 4 to 6

- addons/units/data/uniform_combat_plaid.rvmat
- addons/units/data/uniform_polo.rvmat
- Set the `ambient` & `diffuse` values to match vanilla.
> Units - Darken Plaid and Polo Uniforms

- addons/insignias/CfgUnitInsignia.hpp
> Alphapetize Insignia

- addons/units/stringtable.xml
> Units - Fix ATACS AT-X uniform name

- addons/arcadian/base/config_misc.hpp
> Arcadian - Add Heavy Lifter compatibility

- addons/arcadian/base/config_turret_rear.hpp
> Arcadian - Disable ejection from rear gunner when dead

- addons/arcadian/base/config_sound.hpp
- Change to Car attenuation from MRAP one as ACRE doesn't support it.
> Arcadian - Change to Car Attenuation

- addons/arcadian/base/baseclass.hpp
- addons/arcadian/base/config_ace.hpp
- addons/arcadian/script_component.hpp
- ACE Interaction points are too low when automatically added by ACE. This forces the point to a model selection in the center of the model.
> Arcadian - Set interaction points to selection in the center of the model

- addons/vehicles/vehicles/van.hpp
Both types missing `scopeCurator = 2;`
> Vehicles - Show Vans in Zeus

- addons/arcadian/data/model.cfg
- Reversed the angle. Works fine now.
> Arcadian - Fix upside down fuel gauge

- addons/arcadian/base/baseclass.hpp
- addons/arcadian/base/config_acre.hpp
- addons/arcadian/base/config_acre_armed.hpp
- addons/arcadian/base/config_turret_gatling.hpp
> Arcadian - Fix passenger rack access & Disable attenuation for turrets

- addons/units/uniforms/base.hpp
> Units - Increase supply space inside combat uniforms

- addons/arcadian/base/config_turret_gatling.hpp
- First Magazine is 2000Rnd Green Tracer.
- Second Magazine is 1000Rnd Red Tracer.
> Arcadian - Alter magazine loadout

- addons/vehicles/vehicles/hemtt.hpp
- Forgot to inherit a class, Error wasn't showing with CBA loaded for some reason.
> Vehicles - Fix HEMTT broken classes

- addons/vehicles/vehicles/hemtt.hpp
> Vehicles - Fix HEMTT Editor Previews

- addons/vehicles/vehicles/offroad.hpp
- ~~Git gud Joram.~~
- Git gud at reviewing Mike.
> Vehicles - Fix missing baseclass (XEH) for Covered Offroad

- addons/main/config.cpp
> Main - Update loadorder to AoW

- addons/units/data/w1_vip.rvmat
- addons/units/data/w2_vip.rvmat
> Units - Remove tabs from VIP rvmats

- addons/units/CfgWorlds.hpp
- Adds new names
- Alphabetise list.
> Units - Add more Theseus Contractor names

- addons/arcadian/base/config_misc.hpp
- Title
Component is deprecated in TAC Mods.
> Arcadian - Remove Theseus Mods Heavy Lifter config

- addons/vehicles/vehicles/hemtt.hpp
- Title
Just a PRC152 rack accessible by front seats.
> Add ACRE Rack to HEMTTs

- addons/variants_milgp/marciras.hpp
> Variants Milgp - Fix MarCiras Grey/Black typo

- addons/variants_milgp/stringtable.xml
> Variants Military Gear Pack - Rename (Netherlands) GRY to Grijs

- addons/backpacks/stringtable.xml
> Backpacks - Rename (Netherlands) Grey to Grijs

- addons/variants_cup/CfgVehicles.hpp
- Forgot textures on the rolled kneepad variants.
> Variants CUP - Fix rolled kneepads not having textures

- addons/arcadian/stringtable.xml
- addons/backpacks/stringtable.xml
- addons/glasses/stringtable.xml
- addons/headgear/stringtable.xml
- addons/main/stringtable.xml
- addons/units/stringtable.xml
- addons/variants_cup/stringtable.xml
- addons/variants_melb/stringtable.xml
- addons/variants_milgp/stringtable.xml
- addons/vehicles/stringtable.xml
- addons/vests/stringtable.xml
- addons/weapons/stringtable.xml
- optionals/variants_bwa3/stringtable.xml
- Sorts stringtables using `hemtt ln sort`
> All - Sort Stringtables

- addons/units/items/combat_long_plaid_item.hpp
- addons/vests/stringtable.xml
- Missing stringtable entry
- Unused stringtable key
> General - Fix HEMTT 1.14.3 warnings
